// workshop shell
root.add(mesh(new THREE.PlaneGeometry(30,24),new THREE.MeshStandardMaterial({map:floorTex,color:0x28231d,roughness:.98}),[0,0,0],[-Math.PI/2,0,0],false,true));
root.add(mesh(new THREE.PlaneGeometry(30,10),new THREE.MeshStandardMaterial({map:wallTex,color:0x25221d,roughness:.98}),[0,5,-8],[0,0,0],false,true));
for(let i=-3;i<=3;i++)root.add(mesh(new THREE.BoxGeometry(.28,7,.28),mat.wood,[i*3.6,3.5,-7.72]));
for(let i=0;i<5;i++)root.add(mesh(new THREE.BoxGeometry(26,.22,.34),mat.wood,[0,1.3+i*1.35,-7.68]));
// forge
const forge=new THREE.Group();forge.position.set(-5.5,0,-4.6);root.add(forge);forge.add(mesh(new THREE.BoxGeometry(3.2,2.6,2.1),mat.brick,[0,1.3,0]));forge.add(mesh(new THREE.BoxGeometry(1.65,1.35,.12),new THREE.MeshStandardMaterial({color:0x180702,emissive:0xff4a06,emissiveIntensity:2.2,roughness:.7}),[0,1.25,1.07]));forge.add(mesh(new THREE.BoxGeometry(2.5,.18,.2),mat.steel,[0,2.75,.4]));
const fireLight=new THREE.PointLight(0xff6a18,55,11,1.6);fireLight.position.set(-5.2,1.6,-2.8);fireLight.castShadow=true;scene.add(fireLight);
const cool=new THREE.DirectionalLight(0xbfd4e5,2.0);cool.position.set(5,8,4);cool.castShadow=true;cool.shadow.mapSize.set(1024,1024);scene.add(cool);scene.add(new THREE.HemisphereLight(0x778799,0x1e130c,.65));
// window cold light
const winMat=new THREE.MeshBasicMaterial({color:0x8799a3,transparent:true,opacity:.22});root.add(mesh(new THREE.PlaneGeometry(3.2,2.4),winMat,[4.7,4.1,-7.55]));
// stacked molds
for(let i=0;i<8;i++){const g=new THREE.Group();const x=3.6+(i%3)*1.55,z=-5.9+Math.floor(i/3)*1.7;g.add(mesh(new THREE.CylinderGeometry(.7,.76,.72,40),mat.sand,[0,.36,0]));g.add(mesh(new THREE.TorusGeometry(.73,.045,10,48),mat.steel,[0,.7,0],[Math.PI/2,0,0]));g.position.set(x,0,z);root.add(g)}
// main mold
const mold=new THREE.Group();mold.position.set(.35,0,-.25);root.add(mold);
const moldLeft=new THREE.Group(),moldRight=new THREE.Group();mold.add(moldLeft,moldRight);
const bodyGeo=new THREE.CylinderGeometry(1.42,1.55,1.35,64,2,false);const bodyL=mesh(bodyGeo,mat.sand,[0,.675,0]);const bodyR=bodyL.clone();bodyR.material=mat.sand;
moldLeft.add(bodyL);moldRight.add(bodyR);bodyL.scale.x=.505;bodyL.position.x=-.71;bodyR.scale.x=.505;bodyR.position.x=.71;
for(const part of [moldLeft,moldRight]){part.add(mesh(new THREE.TorusGeometry(1.49,.075,12,64),mat.steel,[0,.2,0],[Math.PI/2,0,0]));part.add(mesh(new THREE.TorusGeometry(1.47,.065,12,64),mat.steel,[0,1.05,0],[Math.PI/2,0,0]))}
// top cap and pouring basin
const cap=mesh(new THREE.CylinderGeometry(1.4,1.43,.22,64),mat.sand,[0,1.44,0]);mold.add(cap);const basin=mesh(new THREE.CylinderGeometry(.46,.26,.25,48,1,true),mat.sandDark,[0,1.62,0]);mold.add(basin);const throat=mesh(new THREE.CylinderGeometry(.12,.12,.22,32),new THREE.MeshStandardMaterial({color:0x171310,roughness:.95}),[0,1.43,0]);mold.add(throat);
for(let a=0;a<Math.PI*2;a+=Math.PI/2){const x=Math.cos(a)*1.18,z=Math.sin(a)*1.18;mold.add(mesh(new THREE.CylinderGeometry(.035,.035,.22,12),mat.steel,[x,1.58,z]));}
// bolts + vertical clamps
for(const x of [-1.18,1.18]){mold.add(mesh(new THREE.BoxGeometry(.11,1.55,.16),mat.steel,[x,.77,.93]));mold.add(mesh(new THREE.CylinderGeometry(.11,.11,.11,6),mat.steel,[x,1.42,.95],[Math.PI/2,0,0]));}
// wooden boards workers stand on
for(const x of [-2.15,2.15])root.add(mesh(new THREE.BoxGeometry(1.6,.12,3.1),mat.wood,[x,.075,.1]));
// hidden iron kettle casting
const casting=new THREE.Group();casting.visible=false;mold.add(casting);const kettleBody=mesh(new THREE.SphereGeometry(.92,64,40,0,Math.PI*2,.3,Math.PI-.55),mat.iron,[0,.78,0]);kettleBody.scale.set(1.08,.87,1.0);casting.add(kettleBody);casting.add(mesh(new THREE.CylinderGeometry(.48,.56,.32,48),mat.iron,[0,1.5,0]));
// spout from tapered cylinders
const spout=new THREE.Group();spout.position.set(.72,1.0,.06);spout.rotation.z=-.62;casting.add(spout);spout.add(mesh(new THREE.CylinderGeometry(.19,.3,.95,32),mat.iron,[0,.43,0]));spout.add(mesh(new THREE.CylinderGeometry(.16,.2,.45,32),mat.iron,[0,1.05,0],[0,0,-.18]));
// sand shell reveal layer
const sandShell=mesh(new THREE.SphereGeometry(.955,48,32),new THREE.MeshStandardMaterial({map:sandTex,color:0x766b5a,roughness:1,transparent:true,opacity:.98}),[0,.79,0]);sandShell.scale.set(1.1,.88,1.02);casting.add(sandShell);
// handle
const handleCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(-.73,1.18,0),new THREE.Vector3(-.95,2.1,0),new THREE.Vector3(0,2.62,0),new THREE.Vector3(.95,2.1,0),new THREE.Vector3(.73,1.18,0)]);const handle=mesh(new THREE.TubeGeometry(handleCurve,64,.055,10,false),mat.steel,[0,.65,0]);handle.visible=false;casting.add(handle);
// ladle using lathe
const ladle=new THREE.Group();root.add(ladle);function lathePts(){const pts=[];for(let i=0;i<=18;i++){const y=-.62+i*(1.15/18);const t=i/18;const r=.42+.38*Math.sin(t*Math.PI*.86);pts.push(new THREE.Vector2(r,y))}return pts}
const ladleOuter=mesh(new THREE.LatheGeometry(lathePts(),64),new THREE.MeshStandardMaterial({color:0x33312d,roughness:.74,metalness:.72,side:THREE.DoubleSide}));ladle.add(ladleOuter);const lining=mesh(new THREE.CylinderGeometry(.64,.49,.64,48,1,true),new THREE.MeshStandardMaterial({color:0x7a6e5b,roughness:.98,side:THREE.DoubleSide}),[0,.1,0]);ladle.add(lining);const moltenSurface=mesh(new THREE.CylinderGeometry(.59,.59,.045,48),new THREE.MeshStandardMaterial({color:0xff7a16,emissive:0xff4d00,emissiveIntensity:3.8,roughness:.22}),[0,.42,0]);ladle.add(moltenSurface);const lip=mesh(new THREE.BoxGeometry(.34,.16,.28),mat.steel,[.64,.36,0],[0,0,-.25]);ladle.add(lip);
for(const z of [-.42,.42]){const bar=mesh(new THREE.CylinderGeometry(.035,.035,4.4,12),mat.steel,[0,0,z],[0,0,Math.PI/2]);bar.position.x=-2.0;ladle.add(bar)}
ladle.scale.setScalar(.82);ladle.position.set(state.ladleX,state.ladleY,1.8);
// workers
function makeWorker(x,z,flip=1){const g=new THREE.Group();g.position.set(x,0,z);const torso=mesh(new THREE.CapsuleGeometry(.31,.75,8,18),mat.cloth,[0,1.45,0]);g.add(torso);const head=mesh(new THREE.SphereGeometry(.22,24,18),new THREE.MeshStandardMaterial({color:0x8b6a52,roughness:.85}),[0,2.13,0]);g.add(head);const capW=mesh(new THREE.CylinderGeometry(.24,.28,.12,24),mat.worker,[0,2.31,0]);g.add(capW);for(const sx of [-1,1]){const arm=new THREE.Group();arm.position.set(sx*.3,1.73,0);const upper=mesh(new THREE.CapsuleGeometry(.09,.45,5,10),mat.cloth,[0,-.18,0]);upper.rotation.z=sx*.58;arm.add(upper);const fore=mesh(new THREE.CapsuleGeometry(.075,.42,5,10),mat.cloth,[sx*.18,-.52,0]);fore.rotation.z=sx*.45;arm.add(fore);g.add(arm)}for(const sx of [-1,1]){const leg=mesh(new THREE.CapsuleGeometry(.105,.62,5,10),mat.worker,[sx*.15,.55,0]);leg.rotation.z=sx*.08;g.add(leg)}g.rotation.y=flip>0?.15:-.15;return g}
const workerL=makeWorker(-3.05,1.7,1),workerR=makeWorker(3.05,1.7,-1);root.add(workerL,workerR);
// stream and particle pools
let streamMesh=null;const moltenMat=new THREE.MeshStandardMaterial({color:0xffa12e,emissive:0xff4c00,emissiveIntensity:4,roughness:.18,metalness:.1});const droplets=[];for(let i=0;i<34;i++){const d=mesh(new THREE.SphereGeometry(.035+Math.random()*.03,10,8),moltenMat);d.visible=false;scene.add(d);droplets.push({m:d,v:new THREE.Vector3(),life:0})}
const dust=[];for(let i=0;i<80;i++){const d=mesh(new THREE.SphereGeometry(.012+Math.random()*.025,6,4),new THREE.MeshBasicMaterial({color:0xb0a089,transparent:true,opacity:.18}));d.visible=false;scene.add(d);dust.push({m:d,v:new THREE.Vector3(),life:0})}
function spawnDroplet(pos){const d=droplets.find(x=>x.life<=0);if(!d)return;d.life=.55+Math.random()*.5;d.m.visible=true;d.m.position.copy(pos);d.v.set((Math.random()-.5)*1.0,1.2+Math.random()*1.5,(Math.random()-.5)*1.0)}
function spawnDust(pos){for(let j=0;j<3;j++){const d=dust.find(x=>x.life<=0);if(!d)break;d.life=.8+Math.random()*1.2;d.m.visible=true;d.m.position.copy(pos);d.v.set((Math.random()-.5)*.45,.25+Math.random()*.45,(Math.random()-.5)*.45)}}
function ladleLipWorld(){const p=new THREE.Vector3(.7,.35,0);ladle.localToWorld(p);return p}
function updateStream(t){if(streamMesh){scene.remove(streamMesh);streamMesh.geometry.dispose();streamMesh=null}const s=state.streamOn;if(s<.025)return;const start=ladleLipWorld();const target=new THREE.Vector3(.35,1.64,-.25);const assist=settings.assist/100;const miss=(state.ladleX+1.0)*(.22*(1-assist));target.x+=miss;const turb=settings.turb/100;const sag=clamp(1.0+(start.y-target.y)*.13,.7,1.5);const wobble=Math.sin(t*9)*.045*turb+Math.sin(t*17)*.02*turb;const c1=start.clone().add(new THREE.Vector3(.18,-.25,wobble));const c2=target.clone().add(new THREE.Vector3(-.12,sag*.32,-wobble));const curve=new THREE.CatmullRomCurve3([start,c1,c2,target]);const radius=.035*(settings.stream/78)*(0.72+state.tilt*.5)*(1+Math.sin(t*12)*.035*turb);streamMesh=mesh(new THREE.TubeGeometry(curve,30,radius,10,false),moltenMat);scene.add(streamMesh);moltenMat.emissiveIntensity=2.8+settings.glow/35;if(Math.random()<.15*s){spawnDroplet(target.clone().add(new THREE.Vector3((Math.random()-.5)*.15,.05,(Math.random()-.5)*.15)))}}
// wedges
const wedges=[];for(const x of [-1.42,1.42]){const w=mesh(new THREE.ConeGeometry(.12,.52,4),mat.steel,[x,1.12,-.25],[0,0,x<0?-.25:.25]);w.visible=false;root.add(w);wedges.push(w)}
// final water stream
let waterMesh=null;const waterMat=new THREE.MeshPhysicalMaterial({color:0xc5d9df,roughness:.08,transmission:.45,transparent:true,opacity:.65,ior:1.33});
// glowing specks / forge embers
const emberGeo=new THREE.BufferGeometry();const emberPos=[];for(let i=0;i<120;i++)emberPos.push(-6+Math.random()*2,1+Math.random()*3,-3.2+Math.random()*1.2);emberGeo.setAttribute('position',new THREE.Float32BufferAttribute(emberPos,3));const embers=new THREE.Points(emberGeo,new THREE.PointsMaterial({color:0xff7a25,size:.025,transparent:true,opacity:.55}));scene.add(embers);
function applyScene(i){state.scene=i;state.progress=0;state.wedge=0;state.clean=0;state.finish=0;state.handle=0;state.pour=0;state.moldOpen=0;state.streamOn=0;state.tilt=0;state.ladleX=-1.35;state.ladleY=2.0;casting.visible=i>=7;cap.visible=i<7;basin.visible=i<7;throat.visible=i<7;sandShell.visible=i===8;sandShell.material.opacity=.98;handle.visible=i>=12;handle.position.y=i===11?1.45:0;casting.traverse(o=>{if(o.material&&o!==sandShell&&o!==handle)o.material=i>=10?new THREE.MeshStandardMaterial({map:ironTex,color:0x171918,roughness:i===10?.38:.65,metalness:.7}):o.material});moldLeft.position.x=0;moldRight.position.x=0;wedges.forEach(w=>w.visible=i===6);ladle.visible=i>=1&&i<=5;workerL.visible=workerR.visible=i>=1&&i<=5;$('#sceneTitle').textContent=scenes[i][0];$('#sceneSub').textContent=scenes[i][2];$('#hintMain').textContent=scenes[i][3];$('#hintSub').textContent=scenes[i][1];$('#gesture').textContent=i===6?'☝︎':(i===0?'↔︎':'☝︎');document.querySelectorAll('.scene').forEach((b,k)=>b.classList.toggle('active',k===i));localStorage.setItem('nambu3d-scene',i)}
function showReward(text='できた'){const f=$('#flash'),to=$('#toast');f.style.opacity=(settings.reward/100*.65).toFixed(2);to.textContent=text;to.style.opacity=Math.max(.35,settings.reward/100);setTimeout(()=>{f.style.opacity=0;to.style.opacity=0},550)}
function progressDone(){if(state.progress>=1){state.progress=1;showReward(state.scene===12?'一杯、できた':'鉄が、応えた')}}
function interaction(dx,dy,isTap=false){const i=state.scene,speed=settings.speed/82,weight=settings.weight/82,assist=settings.assist/100;if(i===0){state.yaw+=dx*.004;state.pitch=clamp(state.pitch+dy*.002,-.08,.2)}else if(i===1){state.ladleY=clamp(state.ladleY-dy*.008/weight,1.65,2.65);state.progress=(state.ladleY-1.65)/1.0}else if(i===2){state.ladleX=clamp(state.ladleX+dx*.007/speed,-2.1,-.25);const target=-.65;state.progress=1-clamp(Math.abs(state.ladleX-target)/1.4,0,1);if(assist>.65)state.ladleX=lerp(state.ladleX,target,.03*assist)}else if(i===3){state.tilt=clamp(state.tilt+dy*.0045/speed,0,1);state.streamOn=Math.max(0,(state.tilt-.28)/.72);state.progress=state.streamOn}else if(i===4){state.tilt=clamp(state.tilt+dy*.003/speed,0.45,.85);state.streamOn=.75+Math.sin(performance.now()*.002)*.015*(settings.turb/100);state.progress=clamp(state.progress+Math.abs(dx)*.0006+.004,0,1)}else if(i===5){state.tilt=clamp(state.tilt+dy*.004/speed,0,.72);state.streamOn=Math.max(0,(state.tilt-.16)/.56);state.progress=1-state.streamOn}else if(i===6&&isTap){state.wedge=clamp(state.wedge+1,0,3);state.progress=state.wedge/3;wedges.forEach((w,k)=>{w.position.y-=.11;w.rotation.z+=(k?-.04:.04)});spawnDust(new THREE.Vector3(.35,1.2,-.25))}else if(i===7){const amt=clamp(Math.abs(dx)*.0035,0,.08);state.moldOpen=clamp(state.moldOpen+amt,0,1);state.progress=state.moldOpen;moldLeft.position.x=-state.moldOpen*1.55;moldRight.position.x=state.moldOpen*1.55;spawnDust(new THREE.Vector3(.35,.9,-.25))}else if(i===8){state.clean=clamp(state.clean+(Math.abs(dx)+Math.abs(dy))*.0008,0,1);sandShell.material.opacity=1-state.clean*.96;state.progress=state.clean;if(Math.random()<.45)spawnDust(new THREE.Vector3(.35+Math.random()-.5,.8+Math.random(),-.25+Math.random()-.5))}else if(i===9){state.finish=clamp(state.finish+(Math.abs(dx)+Math.abs(dy))*.0007,0,1);kettleBody.material.roughness=lerp(.8,.36,state.finish);kettleBody.material.color.setHSL(.12,.02,lerp(.10,.18,state.finish));state.progress=state.finish}else if(i===10){state.finish=clamp(state.finish+(Math.abs(dx)+Math.abs(dy))*.0006,0,1);kettleBody.material.roughness=lerp(.58,.22,state.finish);kettleBody.material.color.setRGB(lerp(.07,.12,state.finish),lerp(.075,.13,state.finish),lerp(.07,.12,state.finish));state.progress=state.finish}else if(i===11){state.handle=clamp(state.handle-dy*.004,0,1);handle.position.y=1.45*(1-state.handle);state.progress=state.handle}else if(i===12){state.pour=clamp(state.pour+dy*.0038,0,1);casting.rotation.z=-state.pour*.65;state.progress=state.pour;if(state.pour>.28)updateWater()}progressDone()}
function updateWater(){if(waterMesh){scene.remove(waterMesh);waterMesh.geometry.dispose();waterMesh=null}const s=casting.localToWorld(new THREE.Vector3(1.35,1.55,.06));const e=s.clone().add(new THREE.Vector3(.35,-2.1,.05));const c=new THREE.CatmullRomCurve3([s,s.clone().add(new THREE.Vector3(.18,-.45,0)),e]);waterMesh=mesh(new THREE.TubeGeometry(c,24,.035,8,false),waterMat);scene.add(waterMesh)}
renderer.domElement.addEventListener('pointerdown',e=>{state.drag=true;state.lastX=e.clientX;state.lastY=e.clientY;renderer.domElement.setPointerCapture?.(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(!state.drag)return;const dx=e.clientX-state.lastX,dy=e.clientY-state.lastY;state.lastX=e.clientX;state.lastY=e.clientY;interaction(dx,dy,false)});renderer.domElement.addEventListener('pointerup',e=>{if(state.drag){const dx=Math.abs(e.clientX-state.lastX),dy=Math.abs(e.clientY-state.lastY);if(dx+dy<7)interaction(0,0,true)}state.drag=false});
