import { chromium } from '@playwright/test'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const page = await browser.newPage({ viewport: { width: 390, height: 844 } })
page.on('console', m => console.log('PAGE:', m.type(), m.text().slice(0,200)))
page.on('pageerror', e => console.log('PAGEERR:', e.message))
await page.goto('http://127.0.0.1:5173/?e2e=1&seed=1', { waitUntil: 'networkidle' })
await page.waitForFunction(() => window.__game !== undefined)
await page.mouse.move(195, 600)
await page.mouse.down()
await page.mouse.move(195, 500, { steps: 8 })
await page.waitForTimeout(300)
console.log('debug', JSON.stringify(await page.evaluate(() => window.__game.debug())))
await page.waitForTimeout(2000)
console.log('state', JSON.stringify(await page.evaluate(() => { const s = window.__game.state(); return {carY:s.carY, tension:s.tension, hookY:s.hookY} })))
await browser.close()
