import { chromium } from 'playwright';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=swiftshader','--enable-unsafe-swiftshader','--mute-audio'] });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, hasTouch: true, isMobile: true });
const page = await ctx.newPage();
page.on('pageerror', (e) => console.log('PAGEERROR', e.message));
await page.goto('http://127.0.0.1:4173/?fast=1', { waitUntil: 'load' });
await page.waitForFunction(() => !!window.__game);
await sleep(2500);
const tips = await page.evaluate(() => window.__game.projectEarTips());
await page.mouse.click(tips.x, tips.y);
await sleep(4000);
const c = await page.evaluate(() => window.__game.projectChest(0, 0.3));
await page.mouse.move(c.x, c.y); await page.mouse.down();
await sleep(9000);
console.log('stage', (await page.evaluate(() => window.__game.snapshot())).stage);
console.log(JSON.stringify(await page.evaluate(() => {
  const g = window.__game;
  const p = g.projectChest(0, 0.3);
  const m = g.projectChest(0.62, -0.36);
  return { centre: { p, s: g.probeTorso(p.x, p.y - 44) }, mitral: { m, s: g.probeTorso(m.x, m.y - 44) } };
}), null, 1));
await page.mouse.up();
await browser.close();
